### ISSUE TITLE
Crash while opening file

### ISSUE THREAD

**Issue by ProfJanetDavis** [WhitmanSWDesignSpring2018/project-5-8-teamalfalfa#110]
This looks hard to debug...

<pre>
[10:48am] janet@brick (~/370/Grading/project-5-8-teamalfalfa/src): java tunecomposer.TuneComposer
May 08, 2019 10:49:00 AM javafx.fxml.FXMLLoader$ValueElement processValue
WARNING: Loading FXML document with JavaFX API of version 10.0.1 by JavaFX runtime of version 8.0.111
objc[16465]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fff8f3803c8) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x12114ef50). One of the two will be used. Which one is undefined.
Exception in thread "JavaFX Application Thread" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at javafx.fxml.FXMLLoader$MethodHandler.invoke(FXMLLoader.java:1774)
	at javafx.fxml.FXMLLoader$ControllerMethodEventHandler.handle(FXMLLoader.java:1657)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.control.MenuItem.fire(MenuItem.java:462)
	at com.sun.javafx.scene.control.skin.ContextMenuContent$MenuItemContainer.doSelect(ContextMenuContent.java:1405)
	at com.sun.javafx.scene.control.skin.ContextMenuContent$MenuItemContainer.lambda$createChildren$343(ContextMenuContent.java:1358)
	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3757)
	at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
	at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:380)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:294)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$354(GlassViewEventHandler.java:416)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:415)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
	at com.sun.glass.ui.View.notifyMouse(View.java:937)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:71)
	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:275)
	at javafx.fxml.FXMLLoader$MethodHandler.invoke(FXMLLoader.java:1769)
	... 40 more
Caused by: java.lang.NullPointerException
	at java.io.FileInputStream.<init>(FileInputStream.java:130)
	at java.io.FileReader.<init>(FileReader.java:72)
	at tunecomposer.CompositionParser.fileToInputSource(CompositionParser.java:137)
	at tunecomposer.TuneComposer.handleOpen(TuneComposer.java:764)
	... 50 more
2019-05-08 10:50:53.512 java[16465:2282342] unrecognized type is 4294967295
2019-05-08 10:50:53.512 java[16465:2282342] *** Assertion failure in -[NSEvent _initWithCGEvent:eventRef:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/AppKit/AppKit-1671.40.119/AppKit.subproj/NSEvent.m:1977
2019-05-08 10:50:53.513 java[16465:2282342] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid parameter not satisfying: _type > 0 && _type <= kCGSLastEventType'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff33cf9cf9 __exceptionPreprocess + 256
	1   libobjc.A.dylib                     0x00007fff5e889a17 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff33d14a16 +[NSException raise:format:arguments:] + 98
	3   Foundation                          0x00007fff35fa6e11 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 194
	4   AppKit                              0x00007fff312d3257 -[NSEvent _initWithCGEvent:eventRef:] + 3296
	5   AppKit                              0x00007fff3161f557 +[NSEvent eventWithCGEvent:] + 117
	6   libglass.dylib                      0x000000010eb1f96b listenTouchEvents + 59
	7   SkyLight                            0x00007fff591d3454 _ZL19processEventTapDataPvjjjPhj + 157
	8   SkyLight                            0x00007fff590d3d64 _XPostEventTapData + 277
	9   SkyLight                            0x00007fff591d3359 _ZL22eventTapMessageHandlerP12__CFMachPortPvlS1_ + 132
	10  CoreFoundation                      0x00007fff33c5bbf9 __CFMachPortPerform + 246
	11  CoreFoundation                      0x00007fff33c5baf7 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__ + 41
	12  CoreFoundation                      0x00007fff33c5ba55 __CFRunLoopDoSource1 + 527
	13  CoreFoundation                      0x00007fff33c43a3c __CFRunLoopRun + 2524
	14  CoreFoundation                      0x00007fff33c42e0e CFRunLoopRunSpecific + 455
	15  HIToolbox                           0x00007fff32f2f9db RunCurrentEventLoopInMode + 292
	16  HIToolbox                           0x00007fff32f2f715 ReceiveNextEventCommon + 603
	17  HIToolbox                           0x00007fff32f2f4a6 _BlockUntilNextEventMatchingListInModeWithFilter + 64
	18  AppKit                              0x00007fff312c9ffb _DPSNextEvent + 965
	19  AppKit                              0x00007fff312c8d93 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1361
	20  libglass.dylib                      0x000000010eb0d72c +[GlassApplication enterNestedEventLoopWithEnv:] + 172
	21  libglass.dylib                      0x000000010eb0e16a Java_com_sun_glass_ui_mac_MacApplication__1enterNestedEventLoopImpl + 74
	22  ???                                 0x00000001115cb9f4 0x0 + 4586256884
	23  ???                                 0x00000001115bc040 0x0 + 4586192960
)
libc++abi.dylib: terminating with uncaught exception of type NSException
Abort
[10:50am] janet@brick (~/370/Grading/project-5-8-teamalfalfa/src): 
</pre>

**Comment by ProfJanetDavis** [comment]
On my Mac.
